= DocOps at https://flowconf.ru/[Flow 2022]

This repository follows the discussion at the round table "DocOps for system analyst" held at https://flowconf.ru/[Flow 2022].

It defines Kotlin DSL Asciidoc wrapper and contains a report on DocOps talks at Flow. The report is written with the help of this wrapper. The report is published at https://habr.com/[Habr]

.Outputs formats
* https://fiddlededee.github.io/flow-2022-docops/flow-docops.html[Html]
* https://fiddlededee.github.io/flow-2022-docops/flow-docops.pdf[Pdf]
* https://fiddlededee.github.io/flow-2022-docops/flow-docops.docx[Microsoft Word (docx)]
* https://fiddlededee.github.io/flow-2022-docops/flow-docops.md[Habr Markdown]
* https://fiddlededee.github.io/flow-2022-docops/flow-docops.txt[Just text]

.Some notes
* Wrapper allows to create Asciidoc files and Habr MarkDown files for publishing at Habr
* Only a subset of Asciidoc directives necessary for the Habr post is implemented
* Applying language tools during abstract syntax tree construction and throwing exception in the case of grammar error is a quick way to navigate to the source of error via stack trace
* MS Word and pdf outputs are created with the help of https://github.com/CourseOrchestra/asciidoctor-open-document[Open Document converter for Asciidoctor]
